[environment_parameters]
label = "portfolio" 
block_rate = 10.0
seed = 0

[price_process_parameters]
# The following constants are used to configure the Ornstein-Uhlenbeck process
# The initial price of the asset.
initial_price = 1.0
# The mean (price) of the process.
mean = 1.0
# The standard deviation of the process.
std_dev = 0.001
# The theta parameter of the process.
# This describes how strongly the process will revert to the mean.
theta = 3.0
# The start time of the process.
t_0 = 0.0
# The end time of the process.
t_n = 1000
# t_n = 1
# The number of steps in the process.
num_steps = 25000
# Seed for the price processes
seed = 1

# We will need two tokens for the simulation.
# One will be the "asset", the other will be the "quote"

[asset_token_parameters]
name = "Arbiter Token X"
symbol = "ARBX"
decimals = 18

[quote_token_parameters]
name = "Arbiter Token Y"
symbol = "ARBY"
decimals = 18


# We need to set the parameters for the Portfolio pool
[portfolio_pool_parameters]
volatility_basis_points = 10
strike_price = 1.0
time_remaining_years = 1
is_perpetual = true
fee_basis_points = 5
priority_fee_basis_points = 0

# LP PARAMETRER
liquidity_mantissa = 1
liquidity_exponent = 20
initial_price = 1.0


# Simulation Parameters
[simulation_parameters]
number_of_paths = 1

# [simulation_parameters.sweep_parameters]
#     [simulation_parameters.sweep_parameters.sweeps.volatility_basis_points]
#     start = 20
#     end = 30
#     steps = 10

#     [simulation_parameters.sweep_parameters.sweeps.fee_basis_points]
#     start = 5
#     end = 100
#     steps = 5